config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root 'pins#index'
  get 'about' => 'pages#about'

  get 'pages/ajax'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def ajax
  	render partial: 'ajax', formats: :html
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @pins = Pin.all
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render :new
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url, notice: 'Pin was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("logo-black.png"), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
          
          <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Pin
            <% end %>
          </li>
          <li><%= link_to "Account Settings", edit_user_registration_path, method: :delete %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<!-- start Mixpanel --><script type="text/javascript">(function(f,b){if(!b.__SV){var a,e,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=f.createElement("script");a.type="text/javascript";a.async=!0;a.src="//cdn.mxpnl.com/libs/mixpanel-2.2.min.js";e=f.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})(document,window.mixpanel||[]);
mixpanel.init("4c1f561aaf9a0bf6ecc7552930c1f2fc");</script><!-- end Mixpanel -->

  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: 'alert alert-info') %>
	<% end %>
	<%= yield %>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55966480-1', 'auto');
  ga('send', 'pageview');

</script>

</body>
</html>

app/views/pages/_ajax.html.erb
<h1>
	Hi I'm Lynn
</h1>

app/views/pages/_home.html.erb
<div class="jumbotron center">

<h1>Welcome to Europe</h1>
  <p>Hello again! Escape to Europe through these photos.</p>
  <p><%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  <%= link_to "Log in", new_user_session_path, class: "btn btn-warning btn-lg" %>
</p>

</div>
<div class="home-container">
  <div class="row">
    <div class="col-sm-12 image1">
      <%= image_tag("sax1.jpg") %>
    </div>
    <div class="col-sm-12 image2">
      <%= image_tag("sax2.jpg") %>
    </div>
    <div class="col-sm-12 image3">
      <%= image_tag("sax3.jpg") %>
    </div>
    <div class="col-sm-12 image4">
      <%= image_tag("sax4.jpg") %>
    </div>
    <div class="col-sm-12 image5">
      <%= image_tag("sax5.jpg") %>
    </div>
  </div>
</div>
  <div class="container home-buttons">
    <div class="btn backward btn-danger" id="backward">
      <p>Backward</p>
    </div>
    <div class="btn restart btn-success" id="restart">
      <p>Restart</p>
    </div>
    <div class="btn forward btn-info" id="forward">
      <p>Forward</p>
    </div>

  </div>

<div id="response"></div>

<button id="call" class="btn btn-lg btn-info" onclick="ajax()">
  CALL
</button>

app/views/pages/about.html.erb
<h1>We are working on our OMR app</h1>

app/views/pages/ajax.html.erb
<h1>
	Hi I'm Lynn
</h1>

app/views/pages/home.html.erb
<div class="jumbotron center">

<h1>Welcome to Europe</h1>
<% if user_signed_in? %>
  <p>Hello again! Escape to Europe through these photos.</p>
<% else %>

  <p><%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  <%= link_to "Log in", new_user_session_path, class: "btn btn-warning btn-lg" %>
</p>
<% end %>

</div>
<div class="home-container">
  <div class="row">
    <div class="col-sm-12 image1">
      <%= image_tag("sax1.jpg") %>
    </div>
    <div class="col-sm-12 image2">
      <%= image_tag("sax2.jpg") %>
    </div>
    <div class="col-sm-12 image3">
      <%= image_tag("sax3.jpg") %>
    </div>
    <div class="col-sm-12 image4">
      <%= image_tag("sax4.jpg") %>
    </div>
    <div class="col-sm-12 image5">
      <%= image_tag("sax5.jpg") %>
    </div>
  </div>
</div>
  <div class="container home-buttons">
    <div class="btn backward btn-danger" id="backward">
      <p>Backward</p>
    </div>
    <div class="btn restart btn-success" id="restart">
      <p>Restart</p>
    </div>
    <div class="btn forward btn-info" id="forward">
      <p>Forward</p>
    </div>

  </div>

<div id="response"></div>

<button id="call" class="btn btn-lg btn-info" onclick="ajax()">
  CALL
</button>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true} do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin%>
      <div class="panel-body">
        <%= pin.description %><br>
        <strong><%= pin.user.email if pin.user %></strong>

        <% if pin.user == current_user %>
          <div class="actions"> 
            <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>Delete
            <% end %>
          </div>
         <% end %>
        
      </div>
      </div>
  <% end %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading center">
			<%= image_tag @pin.image.url(:medium) %>
			</div>
			<div class="panel-body">
				<p><%= @pin.description %></p>
				<p><strong><%= @pin.user.email if @pin.user %></strong></p>
			<% if @pin.user == current_user %>
				<%= link_to edit_pin_path(@pin) do %>
					<span class="glyphicon glyphicon-edit"></span>
					Edit
				<% end %>
			<% end %>
		</div>
	</div>
</div>